/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#725b38",
        "primary-container": "#c5a880",
        "primary-fixed": "#fedeb2",
        "primary-fixed-dim": "#e0c298",
        "on-primary": "#ffffff",
        "on-primary-container": "#513d1d",
        "on-primary-fixed": "#281800",
        "on-primary-fixed-variant": "#584323",

        secondary: "#755a34",
        "secondary-container": "#ffdaab",
        "secondary-fixed": "#ffddb3",
        "secondary-fixed-dim": "#e5c193",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#7a5e38",
        "on-secondary-fixed": "#291800",
        "on-secondary-fixed-variant": "#5b421f",

        tertiary: "#6c5b4d",
        "tertiary-container": "#bda998",
        "tertiary-fixed": "#f5decd",
        "tertiary-fixed-dim": "#d8c3b2",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4c3e31",
        "on-tertiary-fixed": "#25190f",
        "on-tertiary-fixed-variant": "#534437",

        background: "#fcf9f8",
        surface: "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-variant": "#e5e2e1",
        "surface-tint": "#725b38",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",

        "on-surface": "#1c1b1b",
        "on-surface-variant": "#4d463c",
        "on-background": "#1c1b1b",

        outline: "#7f766a",
        "outline-variant": "#d1c5b8",

        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#e0c298",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        // Specialized Luxury Tokens
        asra: {
          cream: '#FAF7F2',
          warmCard: '#FDFBF7',
          gold: '#C5A059',
          goldDark: '#997332',
          goldLight: '#E8D5B5',
          dark: '#1A1817',
          charcoal: '#2D2825',
          muted: '#7E766D',
          border: '#E8E1D7',
          emerald: '#133E2B',
          ruby: '#6B1D2F'
        },
        brand: {
          gold: "#C5A880",
          goldLight: "#E8DCB9",
          goldDark: "#9A7B4F",
          sand: "#FBF9F5",
          cream: "#F5EFEB",
          accent: "#8E2800",
          charcoal: "#1A1817",
          dark: "#1C1917",
          card: "#FFFFFF",
          slate: "#4A4543",
          border: "#E6DFD5",
          lightBg: "#FAF7F2",
          deepGold: "#9E7B34",
          muted: "#7C6E63",
          ivory: "#FAF7F2",
          emerald: "#2E6B47",
          emeraldLight: "#EFF8F2",
          green: "#2E5A44",
          greenBg: "#F0F5F2"
        },
        "brand-gold": "#C5A880",
        "brand-goldLight": "#E8DCB9",
        "brand-goldDark": "#9A7B4F",
        "brand-sand": "#FBF9F5",
        "brand-cream": "#F5EFEB",
        "brand-accent": "#8E2800",
        "brand-charcoal": "#1A1817",
        "brand-dark": "#1C1917",
        "brand-card": "#FFFFFF",
        "brand-slate": "#4A4543",
        "brand-border": "#E6DFD5",
        "brand-lightBg": "#FAF7F2",
        "brand-deepGold": "#9E7B34",
        "brand-muted": "#7C6E63",
        "brand-ivory": "#FAF7F2",
        "brand-emerald": "#2E6B47",
        "brand-emeraldLight": "#EFF8F2",
        "brand-green": "#2E5A44",
        "brand-greenBg": "#F0F5F2"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        serif: ["'Playfair Display'", "serif"],
        "serif-luxury": ["'Playfair Display'", "serif"],
        cormorant: ["'Cormorant Garamond'", "serif"],
        cinzel: ["'Cinzel'", "serif"],
        script: ["'Alex Brush'", "cursive"],
        mono: ["monospace"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
        "title-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Playfair Display'", "serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.12em", fontWeight: "600" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "title-sm": ["1rem", { lineHeight: "1.375rem", letterSpacing: "0.015em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-md": ["0.8125rem", { lineHeight: "1rem", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.625rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "0em", fontWeight: "500" }],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "3rem",
        "margin-mobile": "1.25rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      boxShadow: {
        subtle: "0 1px 6px rgba(0, 0, 0, 0.04), 0 2px 16px rgba(0, 0, 0, 0.03)",
        luxury: "0 8px 30px rgba(114, 91, 56, 0.08)",
        card: "0 2px 12px rgba(44, 39, 36, 0.05)"
      }
    },
  },
  plugins: [],
};
